// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz2kt9W6Me407ltOjrIPezD4o60_XWmLg',
    appId: '1:172612996094:web:a4f4b895655b995e790eaf',
    messagingSenderId: '172612996094',
    projectId: 'authentication-tutorial-a5d4c',
    authDomain: 'authentication-tutorial-a5d4c.firebaseapp.com',
    storageBucket: 'authentication-tutorial-a5d4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ekZnIO9rXxRETjKPuewqii0Ozn9N0as',
    appId: '1:172612996094:android:03475ad8000440a8790eaf',
    messagingSenderId: '172612996094',
    projectId: 'authentication-tutorial-a5d4c',
    storageBucket: 'authentication-tutorial-a5d4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE2dZA-CD1PH7oe7xqPBrNl5P1KC5rowI',
    appId: '1:172612996094:ios:5ebcc32e7815eac4790eaf',
    messagingSenderId: '172612996094',
    projectId: 'authentication-tutorial-a5d4c',
    storageBucket: 'authentication-tutorial-a5d4c.appspot.com',
    iosBundleId: 'com.example.flutterAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE2dZA-CD1PH7oe7xqPBrNl5P1KC5rowI',
    appId: '1:172612996094:ios:5ebcc32e7815eac4790eaf',
    messagingSenderId: '172612996094',
    projectId: 'authentication-tutorial-a5d4c',
    storageBucket: 'authentication-tutorial-a5d4c.appspot.com',
    iosBundleId: 'com.example.flutterAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz2kt9W6Me407ltOjrIPezD4o60_XWmLg',
    appId: '1:172612996094:web:97e8c09d63ca4127790eaf',
    messagingSenderId: '172612996094',
    projectId: 'authentication-tutorial-a5d4c',
    authDomain: 'authentication-tutorial-a5d4c.firebaseapp.com',
    storageBucket: 'authentication-tutorial-a5d4c.appspot.com',
  );
}
